services:
    carve_api.describer.api_describer:
        class: Carve\ApiBundle\Describer\ApiDescriber
        tags: ["nelmio_api_doc.route_describer"]

    carve_api.serializer.circular_reference_handler:
        class: Carve\ApiBundle\Serializer\CircularReferenceHandler

    Carve\ApiBundle\Service\DenyManager:
        class: Carve\ApiBundle\Service\DenyManager
        arguments:
            - !tagged_locator "carve_api.object_deny"
