services:
    carve_api.describer.api_describer:
        class: Carve\ApiBundle\Describer\ApiDescriber
        tags: ["nelmio_api_doc.route_describer"]

    carve_api.serializer.circular_reference_handler:
        class: Carve\ApiBundle\Serializer\CircularReferenceHandler

    carve_api.form.type_guesser.doctrine_enum_type_guesser:
        class: Carve\ApiBundle\Form\TypeGuesser\DoctrineEnumTypeGuesser
        arguments:
            - "@doctrine"
        tags: ["form.type_guesser"]

    carve_api.event_subscriber.debug_toolbar_replace_subscriber:
        class: Carve\ApiBundle\EventSubscriber\DebugToolbarReplaceSubscriber
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    Carve\ApiBundle\Service\DenyManager:
        class: Carve\ApiBundle\Service\DenyManager
        arguments:
            - !tagged_locator "carve_api.object_deny"
